from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[2]

SKU_MASTER_FILE = ROOT_DIR / "[LOGage2026] File 01_SKU Master Data.xlsx"
TRANSACTION_FILE = (
    ROOT_DIR
    / "[LOGage2026] File 02_Transaction Log (My Phuoc & Vinh Loc Warehouses).xlsx"
)
DISTRIBUTOR_FILE = ROOT_DIR / "[LOGage 2026] File 03_Distributor Network.xlsx"

OUTPUT_DIR = ROOT_DIR / "outputs" / "round2"
CLEANED_DIR = OUTPUT_DIR / "cleaned"
TABLES_DIR = OUTPUT_DIR / "tables"
CHARTS_DIR = OUTPUT_DIR / "charts"
NOTES_DIR = OUTPUT_DIR / "notes"
Q11_WORKBOOK_OUTPUT = OUTPUT_DIR / "q11_abc_xyz_analysis.xlsx"

CUSTOMER_SEGMENT_OVERRIDE_FILE = ROOT_DIR / "customer_segment_overrides.csv"
Q11_REFERENCE_WORKBOOK = ROOT_DIR / "LOGage2026_Q1.1_ABC_XYZ_Analysis.xlsx"

ASSIGNMENT_START_DATE = "2025-06-01"
ASSIGNMENT_END_DATE = "2025-12-31"
ASSIGNMENT_DOCUMENT_TYPES = ("A/R INVOICE",)

Q11_START_DATE = ASSIGNMENT_START_DATE
Q11_END_DATE = ASSIGNMENT_END_DATE
Q11_DOCUMENT_TYPES = (
    "A/R INVOICE",
    "INVENTORY TRANSFERS",
    "GOODS ISSUE",
    "STOCK COUNT",
    "A/P CREDIT MEMO",
)
Q11_KEEP_MISSING_SKU_MASTER = True
Q11_ABC_A_THRESHOLD = 0.70
Q11_ABC_B_THRESHOLD = 0.90
FAST_MOVING_ABC_QUANTITY = "A"
FAST_MOVING_XYZ_FREQUENCY = "X"

Q11_VARIABILITY_GRAIN = "monthly"
Q11_VARIABILITY_PERIOD_START = ASSIGNMENT_START_DATE
Q11_VARIABILITY_PERIOD_END = ASSIGNMENT_END_DATE
WINSORIZE_LIMITS = None

WAREHOUSE_COORDINATES = {
    "My Phuoc": (11.152, 106.615),
    "Vinh Loc": (10.785, 106.565),
}
